name: create-releases
run-name: Creating Releases
on:
  push:
    tags:
      - "*"
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a release in GitHub
        run: gh release create ${GITHUB_REF#refs/*/}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

  create-binaries:
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Create ${{ matrix.os }} ${{ matrix.arch }} Binary
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -o build/netbox_fzf cmd/main.go
      - name: Add binary to release
        run: gh release upload ${GITHUB_REF#refs/*/} build/netbox_fzf %#%${{ matrix.os }}_${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
