name: create-releases
run-name: Creating Releases
on:
  push:
    tags:
      - "*"
jobs:
  create-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Create Linux x86 Binary
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/linux_x86 cmd/main.go
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86
          path: build/netbox_fzf
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "netbox_fzf,build/*"
